### ISSUE TITLE
Player movement broken on 1.20.1 Sinytra Connector environment

### ISSUE THREAD

**Issue by NoaHimesaka1873** [ImplicitSaber/Forkcart#2] opened 2024-10-23 02:35 UTC
Player movement will not follow camera movement on 1.20.1 (Neo)Forge + Sinytra Connector environment.
Debug log: https://mclo.gs/6DPOMF1

**Comment by ImplicitSaber** [comment] 2024-10-23 04:01
It's probably because of how (Neo)Forge works much differently than Fabric. To make cart camera rotation work in 1.20.1, I had to redirect multiple MatrixStack multiplications in the GameRenderer to make them match newer versions. It would be quite hard to make this work on Sinytra Connector on old versions, but that's not to say it's impossible. It may happen in the future.

**Comment by ImplicitSaber** [comment] 2024-10-23 04:40
Upon further examination, it seems that the problem is already fixed on NeoForge. I'll just remove my hacky Mixin fix if Connector is detected. Edit: that's on 1.21. 1.20.1 did not fix the problem and camera rotation on tracks will be disabled on that version if using Connector

**Comment by ImplicitSaber** [comment] 2024-10-23 23:47
Should now be fixed in 1.20.1-1.1.0-fix2

**Closed as completed by ImplicitSaber** 2024-10-23 23:47 UTC
Labels: bug
